from . import th_school
from . import th_place
from . import th_training_channel
from . import th_training_time
from . import th_block_combine
from . import th_major_combine
from . import th_major
from . import th_object
from . import th_point_range
from . import th_area
from . import th_method
from . import th_admission
from . import th_benchmark
from . import th_search_setting
from . import th_search_conditions
from . import th_exam_location
from . import th_station
